import Foundation
import PamNative
import UIKit
public final class CanvasViewFactory:NativeViewFactory,@unchecked Sendable{public init(){};public func create(context:AnyObject?,emit:@escaping(Data)->Void)->UIView{PamCanvasView(emit:emit)};public func update(view:UIView,properties:[String:WireValue]){(view as?PamCanvasView)?.update(properties)};public func release(view:UIView){}}
private final class PamCanvasView:UIView,@unchecked Sendable{
 private let emit:(Data)->Void;private var commands:[[String:Any]]=[];private var revision:Int64 = -1
 init(emit:@escaping(Data)->Void){self.emit=emit;super.init(frame:.zero);isMultipleTouchEnabled=false;contentMode = .redraw;backgroundColor = .clear};required init?(coder:NSCoder){nil}
 func update(_ values:[String:WireValue]){guard case let.integer(next)?=values["revision"],next != revision,case let.text(json)?=values["displayList"],let data=json.data(using:.utf8),let decoded=try?JSONSerialization.jsonObject(with:data)as?[[String:Any]]else{return};revision=next;commands=decoded;setNeedsDisplay()}
 override func draw(_ rect:CGRect){guard let context=UIGraphicsGetCurrentContext()else{return};for command in commands{guard let kind=command["k"]as?Int,let a=command["a"]as?[Any]else{continue};switch kind{case 1:context.saveGState();case 2:context.restoreGState();case 3:context.translateBy(x:n(a,0),y:n(a,1));case 4:context.rotate(by:n(a,0) * .pi / 180);case 5:context.scaleBy(x:n(a,0),y:n(a,1));case 6:context.clip(to:CGRect(x:n(a,0),y:n(a,1),width:n(a,2),height:n(a,3)));case 7:context.setFillColor(color(s(a,0)).cgColor);context.fill(bounds);case 8:context.setFillColor(color(s(a,4)).cgColor);context.fill(CGRect(x:n(a,0),y:n(a,1),width:n(a,2),height:n(a,3)));case 9:context.setStrokeColor(color(s(a,4)).cgColor);context.setLineWidth(n(a,5));context.stroke(CGRect(x:n(a,0),y:n(a,1),width:n(a,2),height:n(a,3)));case 10:context.setFillColor(color(s(a,3)).cgColor);context.fillEllipse(in:CGRect(x:n(a,0)-n(a,2),y:n(a,1)-n(a,2),width:n(a,2)*2,height:n(a,2)*2));case 11:context.setStrokeColor(color(s(a,4)).cgColor);context.setLineWidth(n(a,5));context.move(to:CGPoint(x:n(a,0),y:n(a,1)));context.addLine(to:CGPoint(x:n(a,2),y:n(a,3)));context.strokePath();case 12:(s(a,0)as NSString).draw(at:CGPoint(x:n(a,1),y:n(a,2)-n(a,3)),withAttributes:[.font:UIFont.systemFont(ofSize:n(a,3)),.foregroundColor:color(s(a,4))]);default:break}}}
 override func touchesBegan(_ touches:Set<UITouch>,with event:UIEvent?){send(1,touches)};override func touchesMoved(_ touches:Set<UITouch>,with event:UIEvent?){send(2,touches)};override func touchesEnded(_ touches:Set<UITouch>,with event:UIEvent?){send(3,touches)};override func touchesCancelled(_ touches:Set<UITouch>,with event:UIEvent?){send(4,touches)}
 private func send(_ kind:Int64,_ touches:Set<UITouch>){guard let point=touches.first?.location(in:self),let data=try?WireMap.encode(["event":.integer(kind),"x":.decimal(Double(point.x)),"y":.decimal(Double(point.y))])else{return};emit(data)}
 private func n(_ a:[Any],_ i:Int)->CGFloat{CGFloat((a.indices.contains(i) ? a[i]as?NSNumber:nil)?.doubleValue ?? 0)};private func s(_ a:[Any],_ i:Int)->String{a.indices.contains(i) ? a[i]as?String ?? "":""};private func color(_ hex:String)->UIColor{var value=hex.trimmingCharacters(in:.whitespacesAndNewlines);if value.hasPrefix("#"){value.removeFirst()};guard value.count==6||value.count==8,var number=UInt64(value,radix:16)else{return.clear};if value.count==6{number=(number<<8)|255};return UIColor(red:CGFloat((number>>24)&255)/255,green:CGFloat((number>>16)&255)/255,blue:CGFloat((number>>8)&255)/255,alpha:CGFloat(number&255)/255)}
}
